name = "CaosDB"
uuid = "e21bfd3d-73c9-4f59-a3e0-ab690b419b1d"
repo = "https://github.com/JuliaDynamics/CaosDB.jl.git"
version = "0.0.1"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
